use crate::rfc8188;
use crate::rfc8188::{EncodingKey, EncryptedPayload, InputKeyingMaterial, Keyid};
use aes_gcm::aead::Buffer;
use aes_gcm::KeyInit;
use elliptic_curve::rand_core::{OsRng, RngCore};
use elliptic_curve::sec1::ToEncodedPoint;
use hkdf::InvalidLength;
use p256::ecdh::EphemeralSecret;
use reqwest::{Client, RequestBuilder};
use sha2::Sha256;
use url::Url;

/// A Subscription suitable for sending push messages. This object contains all the secrets
/// necessary for encoding a push message payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Subscription {
    pub endpoint: Url,

    pub authentication_secret: AuthenticationSecret,

    pub user_agent_public_key: p256::PublicKey,
}

impl EncodingKey for Subscription {
    type Error = Error;

    fn ikm(&self) -> Result<(Keyid, InputKeyingMaterial), Error> {
        let user_agent_public_key = self.user_agent_public_key;
        let application_server_private_key = EphemeralSecret::random(&mut OsRng);
        let application_service_public_key = application_server_private_key.public_key();
        let ecdh_shared_secret =
            application_server_private_key.diffie_hellman(&user_agent_public_key);

        let mut key_info = Vec::new();
        key_info.extend_from_slice(b"WebPush: info\0");
        key_info.extend_from_slice(user_agent_public_key.to_encoded_point(false).as_bytes());
        key_info.extend_from_slice(
            application_service_public_key
                .to_encoded_point(false)
                .as_bytes(),
        );

        let mut ikm = [0u8; 32];

        ecdh_shared_secret
            .extract::<Sha256>(Some(self.authentication_secret.as_ref()))
            .expand(&key_info, &mut ikm)
            .map_err(|e| Error::InvalidOkmLength(e))?;

        Ok((
            Keyid(
                *application_service_public_key
                    .to_encoded_point(false)
                    .to_bytes()
                    .as_array()
                    .unwrap()
            ),
            InputKeyingMaterial(ikm),
        ))
    }
}

impl Subscription {
    pub fn new(
        endpoint: Url,
        authentication_secret: AuthenticationSecret,
        user_agent_public_key: p256::PublicKey,
    ) -> Self {
        Self {
            endpoint,
            authentication_secret,
            user_agent_public_key,
        }
    }

    pub(crate) fn prepare_request<'a, 'b>(
        &'a self,
        client: &Client,
        message: impl Into<&'b [u8]>,
    ) -> Result<RequestBuilder, Error> {
        let encoded_payload = self.encode_message(message)?;
        Ok(client
            .post(self.endpoint.as_str())
            .header("Content-Type", "application/octet-stream")
            .header("Content-Encoding", "aes128gcm")
            .body::<Vec<u8>>((&encoded_payload).into()))
    }

    /// Encode the given message such that it is suitable for sending across this subscription
    /// and will be decrypted by the client. The message contents will be in the appropriate
    /// encoding as specified within the subscription itself.
    fn encode_message<'a, 'b>(
        &'a self,
        message: impl Into<&'b [u8]>,
    ) -> Result<EncryptedPayload, Error> {
        rfc8188::encode(self, message.into()).map_err(|e| Error::FailedToEncryptPayload(e))
    }
}

/// A sequence of 16 octets generated by the user agent to act as a symmetric key and will
/// be mixed into the key generation process as described in
/// [https://datatracker.ietf.org/doc/html/rfc8291#section-3.2](RFC 8291 Section 3.2).
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AuthenticationSecret(pub [u8; 16]);

impl AsRef<[u8]> for AuthenticationSecret {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

/// A sequence of 16 octets generated by the application server and used during the key generation
/// process when registering a new subscription
struct Salt([u8; 16]);

impl Salt {
    fn random() -> Self {
        let mut salt = [0u8; 16];
        OsRng.fill_bytes(&mut salt);
        Self(salt)
    }
}

#[derive(Debug)]
pub(crate) enum Error {
    InvalidOkmLength(InvalidLength),
    InvalidCekLength(InvalidLength),
    InvalidNonceLength(InvalidLength),
    FailedToEncryptPayload(rfc8188::Error),
}

#[cfg(test)]
mod tests {}